# Setup
name:         Блогът на Христомира
tagline:      A responsive theme for your project on GitHub Pages
url: "hsultova.github.io" 
locale:       "bg"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
layout: default
comments: true
plugins:
  - jekyll-feed
