# Setup

name:         Блогът на Христомира
theme: jekyll-theme-architect
url: "hsultova.github.io" 
locale:       "bg"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
layout: default
comments: true
plugins:
  - jekyll-feed
